#ifndef RANDOMJAM_CONSTANT_HPP
#define RANDOMJAM_CONSTANT_HPP

#define WINDOW_LENGTH 1280
#define WINDOW_WIDTH 720
#define TILE_SIZE 70
#define BUTTON_DELAY 0.1
#define MUSIC_ATTENUATION_RATE 5

#endif //RANDOMJAM_CONSTANT_HPP
